---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker

env:
  global:
    - AWS_DEFAULT_REGION="us-east-1"
    # AWS_ACCESS_KEY_ID
    - secure: "odRp73GykLsey37mcuqdLXL9c8sumx9EQzzsPjer5xSiKz65QHfmKjn7\
      RyYkKx1hYVw+vIuUGaSPeuohhkQ7sq6KhLfQculzNueWkB4Ls58N8eKlCcwo9yz4D\
      fbz4LqJyz+xYXVWOKwbE1M6Uuvih5Ynm/1s7HaJLJW5X1MYIAJelBVzPqDRU1LkWA\
      VZ3eokiShvh2RKriq/50q3jDq/OY24J6Xuwa3Sdf4FMyRpbJVbQV25WWp+bWyzz9b\
      DDLKMmxrWSoeR+e5MatsKUT0EdzXNp1LMxi+fk1uRBGkbFlY3JVCiiGZH3TLFyCRp\
      1Ts2Tglxd49mkQg3430tkNoXtlvKdacmYnD09OE/dPf6QHFArzeWYazJxGkhxybM9\
      AO0RwSB8HdKHmiOa4GHg/pNbQeDcpbZOeyoUrXSsNn8bC4Y3+gipbbFYJi3dkuy2J\
      0txRVtm7aF4H27+LzW8ftADTS+6COpHfmb5qj+E7verLkUnug5KsxHViA7IfA2AZp\
      CEZmG4N+cr7Yy79XdDCZU7Ql1NF7OE8L4a1Gt3ddGMRvDQBJy3eNEMNPTWe58p9ry\
      34U8ImcMPmAcTaDbLXFcsqfOqUN5WmTShtMT8IIqyyL9UkILhN5VBS05nwnbo0Em+\
      8tUS6MJzgSyqjj38bOURHbCdBlECrsR/KdLwn3fnac="
    # AWS_SECRET_ACCESS_KEY
    - secure: "Uhz2yQw8lwwSusbD5xZeHdkqAXEmY1zzzDhBYxlSkiC+Yz50PkV+B3y0\
      9ezWiWH/wqzZQh2POeULt9wTiNMV8EXBOwK/Xk4inYzJuvToo+YEjHMCaK0VXxACD\
      8N/GRIHlefkXSZfx8Wk8aYP9E6Ics7aLwFNYinPxsfJPECY4wVv9t8DlHYZlIE3fN\
      HQzhbjae1uVd4AmI+Z7Xy7BfM6L/XBFnxZus/FcBwyG52qpf03eULyzmnQesJFska\
      UrzVF+zlAaaR3LRvs+00W6tNDwPG64J7L5dnQ08qFXeQMkAabnp3t4MkERAmX6HEN\
      pCkKDVtKQ01v8CFLxsrUW7x6ea8A5844o0NXYoUF0xWziNeBbJl5zvw0Fl2FPVHur\
      sF2OpR/qQaQ1Af3hdF44yk3ijGfZsan3MfPwK+quyfa2+2zgjAb1wmxZOLdbHA/Xm\
      NpHL6OouPOQG6xHnxES0I1Z/1YJKAZILAMrLbuDBnND7OqoRY2I4tD1AtUCEIb49V\
      r/DV+YmFBL8rrf9nbq6v1wSBoAs4Eel4fuApmjPfJ4iFxD3+KBxzHLtC5Z2Cgvzob\
      LLpX5/g0bni6xAak6ZGUhFsmTWxvEQLlKoxwmT4ZcfIGsGolyWjWZvHsYablFWcMO\
      spW39Un3lmJLZKOozP9JhAwP9kXoHafuK1knm2tkx4="

# Install terraform and terraform-doc
before_install:
  - >
    wget
    https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip
    -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - go get github.com/segmentio/terraform-docs

# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

install:
  - pip install --upgrade -r requirements-test.txt
script:
  - pre-commit run --all-files
  - molecule test
