---
- name: Import upgrade playbook
  import_playbook: upgrade.yml

- name: Import python playbook
  import_playbook: python.yml

- name: Group hosts by OS distribution
  hosts: all
  tasks:
    - name: Group hosts by OS distribution
      group_by:
        key: os_{{ ansible_distribution }}
- name: Install shadow-utils (Amazon)
  hosts: os_Amazon
  tasks:
    # The Amazon Linux 2 Docker image does not have the groupmod
    # utility installed.
    - name: Install shadow-utils (Amazon-only)
      package:
        name:
          - shadow-utils
