---
- name: Import upgrade playbook
  import_playbook: upgrade.yml

- name: Import python playbook
  import_playbook: python.yml

- name: Prepare
  hosts: all
  tasks:
    # The Amazon Linux 2 Docker image does not have the groupmod
    # utility installed.
    - name: Install shadow-utils (Amazon-only)
      package:
        name:
          - shadow-utils
      when: ansible_distribution == 'Amazon'
