---
name: build

on:
  push:
  pull_request:
  repository_dispatch:
    types: [apb]

env:
  AWS_DEFAULT_REGION: us-east-1
  PIP_CACHE_DIR: ~/.cache/pip
  PRE_COMMIT_CACHE_DIR: ~/.cache/pre-commit

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache linting environments
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.PIP_CACHE_DIR }}
            ${{ env.PRE_COMMIT_CACHE_DIR }}
          key: |
            lint-${{ runner.os }}-\
            py${{ steps.setup-python.outputs.python-version }}-\
            ${{ hashFiles('**/requirements-test.txt') }}-\
            ${{ hashFiles('**/requirements.txt') }}-\
            ${{ hashFiles('**/.pre-commit-config.yaml') }}"
          restore-keys: |
            lint-${{ runner.os }}-\
            py${{ steps.setup-python.outputs.python-version }}-
            lint-${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --requirement requirements-test.txt
      - name: Set up pre-commit hook environments
        run: pre-commit install-hooks
      - name: Run pre-commit on all files
        run: pre-commit run --all-files
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache testing environments
        uses: actions/cache@v2
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: "test-${{ runner.os }}-\
          py${{ steps.setup-python.outputs.python-version }}-\
          ${{ hashFiles('**/requirements-test.txt') }}-\
          ${{ hashFiles('**/requirements.txt') }}"
          restore-keys: |
            test-${{ runner.os }}-\
            py${{ steps.setup-python.outputs.python-version }}-
            test-${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --requirement requirements-test.txt
      - name: Run molecule tests
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: molecule test
